### PR TITLE
Add redis sentinel 

### PR DESCRIPTION
**Pull request by jordanbcooper**
Looking for feedback on this additional job for sentinel. I am happy to further document in the README if there are questions about how this works, but I have built multiple clusters and interacted with them via CLI and our SDK, tested failover, etc. I welcome feedback to make this production ready!

### CODE REVIEW

**Comment by jordanbcooper** [comment]
@jhunt Would you want a manifest for your pipeline to test the sentinel job?

**Comment by drnic** [comment]
@jordanbcooper I'd love three things:

- [ ] bosh operator file to modify base manifest to use sentinel https://github.com/cloudfoundry-community/redis-boshrelease/tree/master/manifests/operators
- [ ] an amendment to the README to mention Sentinel
- [ ] create `ci/release_notes.md` with the contents that will go into GitHub release

**Comment by jordanbcooper** [comment]
Excellent @drnic -- I'll get on those when I return next week!

**Comment by jordanbcooper** [comment]
@drnic , redis-sentinel depends on static IPs. How might I resolve this in an operator when this repo and its operators seem to be using dynamic?

**Comment by jordanbcooper** [comment]
I almost wonder if we ignored people with dynamic IPs already by introducing this to redis config:
https://github.com/cloudfoundry-community/redis-boshrelease/blob/f39a2b53097b29cb23efb80843089709f8f80bfc/jobs/redis/templates/config/redis.conf.erb#L177

**Comment by jordanbcooper** [comment]
Link was it! I will have an operator asap.

**Comment by jordanbcooper** [comment]
@drnic This should be all set.

**Comment by jordanbcooper** [comment]
@drnic Three tasks are complete.

**Comment by drnic** [comment]
@jordanbcooper awesome; merged. I'll investigate testing it in a parallel CI job. Since it doesn't negatively affect the existing jobs, we can probably push it out to a new release before that new CI work.

**Pull request merged**
