### PR TITLE
Allow openstack_cpi

### PR DESCRIPTION
**Pull request by KostyaSha**
CC @axelaris @drnic

### CODE REVIEW

**Comment by KostyaSha** [comment]
PR build failed, travis config should be updated
```
Gem::InstallError: fog-google requires Ruby version >= 2.0.
Installing fog-voxel 0.1.0
An error occurred while installing
```

**Comment by KostyaSha** [comment]
Seems caused by https://www.pivotaltracker.com/n/projects/1133984/stories/105868858

**Comment by KostyaSha** [comment]
Thanks, hope travis will work now.

**Comment by drnic** [comment]
Happy to merge as its unrelated to test failure

**Pull request merged**
